/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KanbanBoard: typeof import('./src/components/KanbanBoard.vue')['default']
    KanbanItem: typeof import('./src/components/KanbanItem.vue')['default']
    KanbanList: typeof import('./src/components/KanbanList.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
